services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hlstatsx
      MYSQL_USER: hlstatsx
      MYSQL_PASSWORD: hlstatsx_password
      HLX_PROXY_KEY: "d7fe18f9c4d10180f2aa6393"
    volumes:
      - hlx-db-data:/var/lib/mysql
      - ./src/sql/install.sql:/tmp/install.sql:ro
      - ./docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db

  daemon:
    build:
      context: .
      dockerfile: docker/daemon/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "27500:27500/udp"

  forwarder:
    build:
      context: .
      dockerfile: docker/forwarder/Dockerfile
    restart: always
    environment:
      PROXY_KEY: "d7fe18f9c4d10180f2aa6393"
      GAME_IP: "192.168.2.99"
      GAME_PORT: "27015"
    command: >
      -forward.proxy-key d7fe18f9c4d10180f2aa6393
      -forward.gameserver-ip 192.168.2.99
      -forward.gameserver-port 27015
      -forward.to-addr daemon:27500

volumes:
  hlx-db-data: