services:
  db:
    image: mariadb:11.8
    container_name: hlx-db
    restart: always
    command: >
      --innodb_buffer_pool_size=${DB_BUFFER_POOL_SIZE:-512M}
      --innodb_flush_log_at_trx_commit=${DB_FLUSH_LOG_AT_TRX_COMMIT:-2}
      --innodb_log_buffer_size=${DB_LOG_BUFFER_SIZE:-16M}
      --max_connections=${DB_MAX_CONNECTIONS:-200}
      --table_open_cache=${DB_TABLE_OPEN_CACHE:-2000}

    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS:-root_password}"
      MYSQL_DATABASE: "${DB_NAME:-hlstatsx}"
      MYSQL_USER: "${DB_USER:-hlstatsx}"
      MYSQL_PASSWORD: "${DB_PASS:-hlstatsx_password}"
      HLX_PROXY_KEY: "${PROXY_KEY:-dummy_key}"
      TZ: "${TZ:-Europe/Budapest}"
    volumes:
      - hlx-db-data:/var/lib/mysql
      - ./docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./src/sql/install.sql:/tmp/install.sql:ro

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: hlx-web
    restart: always
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - db
    environment:
      DB_NAME: "${DB_NAME:-hlstatsx}"
      DB_USER: "${DB_USER:-hlstatsx}"
      DB_PASS: "${DB_PASS:-hlstatsx_password}"
      DB_HOST: "hlx-db"
      DAEMON_HOST: "${DAEMON_HOST:-hlx-daemon}"
      TZ: "${TZ:-Europe/Budapest}"

  daemon:
    build:
      context: .
      dockerfile: docker/daemon/Dockerfile
    container_name: hlx-daemon
    restart: always
    depends_on:
      - db
    ports:
      - "${DAEMON_PORT:-27500}:27500/udp"
      - "${DAEMON_PORT:-27500}:27500/tcp"
    environment:
      DB_NAME: "${DB_NAME:-hlstatsx}"
      DB_USER: "${DB_USER:-hlstatsx}"
      DB_PASS: "${DB_PASS:-hlstatsx_password}"
      DB_HOST: "hlx-db"
      DAEMON_PORT: "27500"
      TZ: "${TZ:-Europe/Budapest}"

  forwarder:
    build:
      context: .
      dockerfile: docker/forwarder/Dockerfile
    container_name: hlx-forwarder
    profiles:
      - forwarder
    restart: always
    environment:
      PROXY_KEY: "${PROXY_KEY:-dummy_key}"
      GAME_SERVER_IP: "${GAME_SERVER_IP:-127.0.0.1}"
      GAME_SERVER_PORT: "${GAME_SERVER_PORT:-27015}"
      DAEMON_HOST: "${DAEMON_HOST:-hlx-daemon}"
      DAEMON_PORT: "27500"
      TZ: "${TZ:-Europe/Budapest}"
    ports:
      - "${FORWARDER_PORT:-26999}:${FORWARDER_PORT:-26999}/udp"
      - "${FORWARDER_PORT:-26999}:${FORWARDER_PORT:-26999}/tcp"
    command: >
      -listen-address :${FORWARDER_PORT:-26999}
      -udp.forward-address ${DAEMON_HOST:-hlx-daemon}:27500
      -forward.proxy-key ${PROXY_KEY:-dummy_key}
      -forward.gameserver-ip ${GAME_SERVER_IP:-127.0.0.1}
      -forward.gameserver-port ${GAME_SERVER_PORT:-27015}

volumes:
  hlx-db-data:
