#!/bin/bash
# HLstatsX Community Edition - Real-time player and clan rankings and statistics
# Copyleft (L) 2008-20XX Nicholas Hastings (nshastings@gmail.com)
# http://www.hlxce.com
#
# HLstatsX Community Edition is a continuation of
# ELstatsNEO - Real-time player and clan rankings and statistics
# Copyleft (L) 2008-20XX Malte Bayer (steam@neo-soft.org)
# http://ovrsized.neo-soft.org/
#
# ELstatsNEO is an very improved & enhanced - so called Ultra-Humongus Edition of HLstatsX
# HLstatsX - Real-time player and clan rankings and statistics for Half-Life 2
# http://www.hlstatsx.com/
# Copyright (C) 2005-2007 Tobias Oetzel (Tobi@hlstatsx.com)
#
# HLstatsX is an enhanced version of HLstats made by Simon Garner
# HLstats - Real-time player and clan rankings and statistics for Half-Life
# http://sourceforge.net/projects/hlstats/
# Copyright (C) 2001  Simon Garner
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# For support and installation notes visit http://www.hlxcommunity.com

#------------------------------------------------------------------------------
# Script Configuration
SCRIPTPATH=.
CONFFILE=hlstats.conf
DAEMON=hlstats.pl
LOGDIR=${SCRIPTPATH}/logs
LOGDATE_FORMAT=%Y-%m-%d_%H-%M-%S
PIDDIR=${SCRIPTPATH}
#------------------------------------------------------------------------------

WEBSITE=http://www.hlxce.com
WIKI=http://wiki.hlxce.com

# Start output
echo
echo "HLstatsX:CE daemon control"
echo "${WEBSITE}"
echo "---------------------------"

# Change to directory of script
cd "$(dirname "$0")"

# Perform some initial checks
if [ ! -w "${SCRIPTPATH}" ]; then
        echo "CRITICAL ERROR: Could not write to SCRIPTPATH: ${SCRIPTPATH}"
        echo "Verify you have write access to this directory."
        exit 1
fi

if [ ! -f "${SCRIPTPATH}/${DAEMON}" ]; then
        echo "CRITICAL ERROR: Cannot access the daemon: ${DAEMON}"
        echo "Verify that the daemon, and corresponding files, exist in ${SCRIPTPATH}"
        exit 1
fi

SHEBANG=$(head -n1 "${SCRIPTPATH}/${DAEMON}")
if [[ ${SHEBANG} =~ ^#! ]]; then
  SHEBANG_BINARY=$(echo "${SHEBANG}" | sed 's/^#!//')
  if [ ! -f "${SHEBANG_BINARY}" ]; then
    echo "CRITICAL ERROR: The path to Perl is incorrect in ${DAEMON}."
    echo "Current Perl path in shebang: ${SHEBANG_BINARY}"
    echo
    echo "Potential paths for Perl: "
    which perl
    exit 1
  fi
else
    echo "CRITICAL ERROR: The shebang line is incorrectly configured in ${DAEMON}."
    exit 1
fi

if [ ! -d "${LOGDIR}" ]; then
        mkdir -p "${LOGDIR}"
fi

if [ ! -w "${LOGDIR}" ]; then
        echo "CRITICAL ERROR: Could not write to the log folder: ${LOGDIR}"
        exit 1
fi

function start_daemon {
        if [ ! "$1" ]; then
                echo "CRITICAL ERROR: No port was received on function start_daemon"
                exit 1
        else
                local PORT=$1
        fi

        local LOG=${LOGDIR}/hlstats_${PORT}_$(date +${LOGDATE_FORMAT}).log
        local PID=$(get_pid "${PORT}")

        if [ -n "${PID}" ]; then
                kill -0 "${PID}" &> /dev/null
                if [ $? -eq 0 ]; then
                        return 2
                else
                        remove_pidfile "${PORT}"
                fi
        fi

        echo -ne "Attempting to start HLstatsX:CE daemon on port ${PORT}..."
        "${SCRIPTPATH}/${DAEMON}" --configfile="${CONFFILE}" --port="${PORT}" &> "${LOG}" &
        PID=$!

        kill -0 "${PID}" &> /dev/null
        if [ $? -eq 0 ]; then
                create_pidfile "${PORT}" "${PID}"
                echo ""
                return 0
        else
                local i=1
                while [ $i -le 10 ]
                do
                        echo -ne " ${i}"
                        sleep 1
                        kill -0 "${PID}" &> /dev/null
                        if [ $? -eq 1 ]; then
                                let i++
                                if [ $i -eq 10 ]; then
                                        return 1
                                fi
                        else
                                create_pidfile "${PORT}" "${PID}"
                                echo ""
                                return 0
                        fi
                done
        fi
}

function stop_daemon {
        if [ ! "$1" ]; then
                echo "CRITICAL ERROR: No port was received on function stop_daemon"
                exit 1
        else
                local PORT=$1
        fi

        local PID=$(get_pid "${PORT}")

        if [ -z "${PID}" ]; then
                return 3
        fi

        echo -n "Attempting graceful shutdown of HLstatsX:CE daemon on port ${PORT} "
        kill -INT "${PID}" &> /dev/null

        if [ $? -ne 0 ]; then
                remove_pidfile "${PORT}"
                echo ""
                return 3
        else
                kill -0 "${PID}" &> /dev/null
                if [ $? -eq 1 ]; then
                        remove_pidfile "${PORT}"
                        echo ""
                        return 0
                else
                        local i=1
                        while [ $i -le 10 ]
                        do
                                echo -n " ${i}"
                                sleep 1
                                kill -0 "${PID}" &> /dev/null
                                if [ $? -eq 0 ]; then
                                        let i++
                                else
                                        remove_pidfile "${PORT}"
                                        echo ""
                                        return 0
                                fi
                        done
                fi

                echo ""
                echo "WARNING: Daemon did not respond to graceful shutdown. Forcing shutdown on port ${PORT} "
                local i=1
                while [ $i -le 5 ]
                do
                        kill -KILL "${PID}" &> /dev/null
                        echo -n " ${i}"
                        sleep 1
                        kill -0 "${PID}" &> /dev/null
                        if [ $? -eq 0 ]; then
                                let i++
                        else
                                remove_pidfile "${PORT}"
                                echo ""
                                return 1
                        fi
                done
                return 2
        fi
}

function reload_daemon {
        if [ ! "$1" ]; then
                echo "CRITICAL ERROR: No port was received on function reload_daemon"
                exit 1
        else
                local PORT=$1
        fi

        local PID=$(get_pid "${PORT}")
        if [ -n "${PID}" ]; then
                kill -0 "${PID}" &> /dev/null
                if [ $? -eq 0 ]; then
                        kill -HUP "${PID}" &> /dev/null
                        return 0
                else
                        return 1
                fi
        else
                return 1
        fi
}

function check_port {
        if [ "$1" ]; then
                echo "$1" | grep -q -E '^[0-9]{1,5}$'
                if [ $? -eq 0 ] && [ "$1" -le 65535 ] && [ "$1" -ge 1 ]; then
                        return 0
                else
                        return 1
                fi
        fi
}

function get_status {
        if [ "$1" ]; then
                local PID=$(get_pid "$1")
                if [ -n "${PID}" ]; then
                        kill -0 "${PID}" &> /dev/null
                        if [ $? -eq 0 ]; then
                                return 0
                        else
                                return 1
                        fi
                else
                        return 2
                fi
        fi
}

function create_pidfile {
        if [[ $1 && $2 ]]; then
                PIDFILE=${PIDDIR}/hlstats_${1}.pid
                echo "${2}" > "${PIDFILE}"
                if [ "$(cat "${PIDFILE}")" -eq "${2}" ]; then
                        return 0
                else
                        return 1
                fi
        fi
}

function remove_pidfile {
        if [ "$1" ]; then
                PIDFILE=${PIDDIR}/hlstats_${1}.pid
                rm -f "${PIDFILE}" &> /dev/null
                return 0
        fi
}

function get_pid {
        if [ "$1" ]; then
                PIDFILE=${PIDDIR}/hlstats_${1}.pid
                PID=$(cat "${PIDFILE}" 2> /dev/null)
                if [ $? -eq 0 ]; then
                        echo "${PID}"
                        return 0
                else
                        return 1
                fi
        fi
}

if [ -f "${PIDDIR}/hlstats.pid" ]; then
        echo "WARNING: A legacy PID file has been detected. Shutting it down."
        kill -KILL "$(cat "${PIDDIR}/hlstats.pid")" &> /dev/null
        rm -f "${PIDDIR}/hlstats.pid"
fi

case "$1" in
        start)
                NUMDAEMONS=1
                STARTPORT=27500
                INCREMENT=1

                if [ "$2" ]; then
                        NUMDAEMONS=$2
                fi

                if [ "$3" ]; then
                        check_port "$3"
                        if [ $? -eq 0 ]; then
                                STARTPORT=$3
                        else
                                echo "CRITICAL ERROR: An invalid port number was specified."
                                exit 1
                        fi
                fi

                if [ "$4" ]; then
                        INCREMENT=$4
                fi

                i=0
                CURRENTPORT=${STARTPORT}
                while [ ${i} -lt ${NUMDAEMONS} ]
                do
                        start_daemon ${CURRENTPORT}
                        case $? in
                                0)
                                        echo "Daemon successfully started on port ${CURRENTPORT}"
                                        let CURRENTPORT=CURRENTPORT+INCREMENT
                                        let i++
                                ;;
                                1)
                                        echo "CRITICAL ERROR: Unable to start daemon on port ${CURRENTPORT}"
                                        exit 1
                                ;;
                                2)
                                        echo "Daemon is already running on port ${CURRENTPORT}"
                                        let CURRENTPORT=CURRENTPORT+INCREMENT
                                        let i++
                                ;;
                        esac
                done
        ;;

        stop)
                if [ "$2" ]; then
                        check_port "$2"
                        if [ $? -eq 0 ]; then
                                PORT=$2
                        else
                                echo "CRITICAL ERROR: An invalid port number was specified."
                                exit 1
                        fi
                else
                        PORT=0
                fi

                if [ ${PORT} -ne 0 ]; then
                        stop_daemon ${PORT}
                        case $? in
                                0)
                                        echo "Daemon gracefully stopped on port ${PORT}"
                                        exit 0
                                ;;
                                1)
                                        echo "Daemon forcefully stopped on port ${PORT}"
                                        exit 0
                                ;;
                                2)
                                        echo "WARNING: Daemon could not be stopped on port ${PORT}"
                                        exit 1
                                ;;
                                3)
                                        echo "No daemon running on port ${PORT} or PID file is missing."
                                        exit 1
                                ;;
                        esac
                fi

                PORTS=$(ls ${PIDDIR} 2>/dev/null | grep -E 'hlstats_[0-9]{1,5}\.pid' | grep -o -E '[0-9]{1,5}')
                if [ -n "${PORTS}" ]; then
                        for port in ${PORTS} ; do
                                stop_daemon ${port}
                        done
                else
                        echo "No daemons found running, or PID files are missing."
                        exit 1
                fi
        ;;

        restart)
                if [ "$2" ]; then
                        check_port "$2"
                        if [ $? -eq 0 ]; then
                                PORT=$2
                        else
                                echo "CRITICAL ERROR: An invalid port number was specified."
                                exit 1
                        fi
                else
                        PORT=0
                fi

                if [ ${PORT} -ne 0 ]; then
                        stop_daemon ${PORT}
                        start_daemon ${PORT}
                        if [ $? -eq 0 ]; then
                                echo "Daemon successfully restarted on port ${PORT}"
                                exit 0
                        else
                                echo "CRITICAL ERROR: Failed to restart daemon on port ${PORT}"
                                exit 1
                        fi
                fi

                PORTS=$(ls ${PIDDIR} 2>/dev/null | grep -E 'hlstats_[0-9]{1,5}\.pid' | grep -o -E '[0-9]{1,5}')
                if [ -n "${PORTS}" ]; then
                        for port in ${PORTS} ; do
                                stop_daemon ${port}
                                start_daemon ${port}
                        done
                else
                        echo "WARNING: No HLstatsX:CE daemons currently running."
                        exit 1
                fi
        ;;

        reload)
                if [ "$2" ]; then
                        check_port "$2"
                        if [ $? -eq 0 ]; then
                                PORT=$2
                        else
                                echo "CRITICAL ERROR: An invalid port number was specified."
                                exit 1
                        fi
                else
                        PORT=0
                fi

                if [ ${PORT} -ne 0 ]; then
                        reload_daemon ${PORT}
                        if [ $? -eq 0 ]; then
                                echo "Successfully reloaded daemon running on port ${PORT}"
                                exit 0
                        else
                                echo "WARNING: Unable to reload daemon on port ${PORT}"
                                exit 1
                        fi
                fi

                PORTS=$(ls ${PIDDIR} 2>/dev/null | grep -E 'hlstats_[0-9]{1,5}\.pid' | grep -o -E '[0-9]{1,5}')
                if [ -n "${PORTS}" ]; then
                        for port in ${PORTS} ; do
                                reload_daemon ${port}
                        done
                else
                        echo "WARNING: No HLstatsX:CE daemons currently running."
                        exit 1
                fi
        ;;

        status)
                if [ "$2" ]; then
                        check_port "$2"
                        if [ $? -eq 0 ]; then
                                PORT=$2
                        else
                                echo "CRITICAL ERROR: An invalid port number was specified."
                                exit 1
                        fi
                else
                        PORT=0
                fi

                if [ ${PORT} -ne 0 ]; then
                        get_status ${PORT}
                        case $? in
                                0)
                                        echo "Daemon on port ${PORT} is currently running."
                                        exit 0
                                ;;
                                1)
                                        echo "A stale process was found for daemon on port ${PORT}."
                                        exit 0
                                ;;
                                2)
                                        echo "There is no daemon running on port ${PORT}."
                                        exit 0
                                ;;
                        esac
                fi

                PORTS=$(ls ${PIDDIR} 2>/dev/null | grep -E 'hlstats_[0-9]{1,5}\.pid' | grep -o -E '[0-9]{1,5}')
                if [ -n "${PORTS}" ]; then
                        for port in ${PORTS} ; do
                                get_status ${port}
                        done
                else
                        echo "WARNING: No HLstatsX:CE daemons currently running."
                        exit 1
                fi
        ;;

        *)
                echo "Usage:"
                echo -e "\trun_hlstats start   <number of daemons (1)> <starting port number (27500)> <port increment (1)>"
                echo -e "\trun_hlstats stop    <port # of daemon to stop (ALL)>"
                echo -e "\trun_hlstats status  <port # of daemon to check status of (ALL)>"
                echo -e "\trun_hlstats restart <port # of daemon to restart (ALL)>"
                echo -e "\trun_hlstats reload  <port # of daemon to reload (ALL)>"
        ;;
esac
exit 0